### PR TITLE
Accelerate fastaptamer_cluster using Text::LevenshteinXS

### PR DESCRIPTION
**Pull request by vladimirkhramkov**
Accelerate fastaptamer_cluster using Text::LevenshteinXS module instead of internal implementation

### CODE REVIEW

**Comment by molecules** [comment]
FASTAptamer was designed to have no runtime dependencies outside of core Perl modules. However, we could probably make it conditionally use Text::LevenshteinXS or Text::Levenshtein::XS, if present.

How much faster is it, by the way?

**Comment by vladimirkhramkov** [comment]
Text::LevenshteinXS implementation is faster about 250-1000 times than yours. Using Text::LevenshteinXS distance function makes fastaptamer_cluster program to run 50-100 times faster than original implementation. So I think it worse to use Text::LevenshteinXS module or rewrite internal levenshtein function.

**Comment by FASTAptamer** [comment]
As Chris (molecules) suggested, FASTAptamer is designed for and used by command line novices. As such, we deliberately made the decision to forego implementations that would run faster at the expense of complicating the user experience. I would welcome an implementation that would allow for users to run the XS implementation as a command line option or as a standalone script.

**Comment by molecules** [comment]
Implemented as fastaptamer_cluster_xs in [release v1.0.12](https://github.com/FASTAptamer/FASTAptamer/tree/v1.0.12). Thanks vladimirkhramkov!

**Pull request closed without merging**
